[package]
org = "ballerina"
name = "os"
version = "1.0.1"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/os-native-1.0.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/io-native-1.0.0.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/os-test-utils-1.0.1-SNAPSHOT.jar"
