[package]
org = "ballerina"
name = "os"
version = "1.2.2"
authors = ["Ballerina"]
keywords = ["environment"]
repository = "https://github.com/ballerina-platform/module-ballerina-os"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.1"

[[platform.java11.dependency]]
path = "../native/build/libs/os-native-1.2.2-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/io-native-1.2.1.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/os-test-utils-1.2.2-SNAPSHOT.jar"
